apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: servicex
      version: '1.0.7'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
