apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: servicex
      version: '1.0.8-0'
      sourceRef:
        kind: HelmRepository
        name: servicex
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
